runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /semantic
  static_dir: semantic
  secure: always
- url: /resources
  static_dir: resources
  secure: always
- url: /
  script: broker.app
  secure: always
- url: /store
  script: broker.app
  secure: always
- url: /login
  script: broker.app
  secure: always
  login: required


libraries:
- name: webapp2
  version: latest
- name: ssl
  version: latest
